apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
  labels:
    app: service
    type: portfolio
  namespace: personal-projects
spec:
  type: NodePort
  selector:
      app: pod
      type: portfolio
  ports:
    - protocol: TCP 
      port: 5173
      targetPort: 80

  
